serviceAccount:
  create: true
  name: tempo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::474589087003:role/TempoRole
retention: 48h
storage:
  capacity: 30G
  storageClassName: local-path
backend: {}
distributor:
  serviceAccountName: tempo
  replicas: 2
  image: grafana/tempo:latest
  resources: 
    requests:
      cpu:      1
      memory:   500Mi
  receivers:
    jaeger:
      protocols:
        thrift_http: null
compactor:
  serviceAccountName: tempo
  replicas: 1
  image: grafana/tempo:latest
  resources: 
    requests:
      cpu:      250m
      memory:   1Gi
ingester:
  serviceAccountName: tempo
  replicas: 3
  image: grafana/tempo:latest
  resources: 
    requests:
      cpu:      1
      memory:   1.5Gi
resources:
  image: grafana/tempo:latest
  resources: 
    requests:
      cpu:      500m
      memory:   2Gi
queryFrontend:
  serviceAccountName: tempo
  replicas: 1
  image: grafana/tempo:latest
  resources:
    requests:
      cpu:      250m
      memory:   500Mi
querier:
  serviceAccountName: tempo
  replicas: 1
  image: grafana/tempo:latest
  resources: 
    requests:
      cpu:      250m
      memory:   500Mi
tempoQuery:
  image: grafana/tempo-query:latest
  resources: 
    requests:
      cpu:      50m
      memory:   100Mi
memcached:
  image: memcached:1.5.17-alpine
  replicas: 0

