apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-querier
data:
  tempo.yaml: |
    auth_enabled: false
    querier:
        frontend_worker:
            frontend_address: query-frontend-discovery.tracing.svc.cluster.local:9095
            grpc_client_config:
                max_recv_msg_size: 104857600
                max_send_msg_size: 16777216
            #    # max_send_msg_size: 33554432
        # max_concurrent_queries: 10
        # query_timeout: 20
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
          - gossip-ring.tracing.svc.cluster.local:7946
    overrides:
        per_tenant_override_config: /conf/overrides.yaml
    server:
        http_listen_port: 3100
        log_level: debug
    storage:
        trace:
            {{- toYaml .Values.backend | nindent 12 }}
            blocklist_poll: 5m
            cache: memcached
            memcached:
                consistent_hash: true
                host: memcached
                service: memcached-client
                timeout: 1s
            pool:
                max_workers: 200
                queue_depth: 2000
            wal:
                path: /var/tempo/wal
