{{- if .Values.serviceAccount.create }}
{{- with .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  {{- if .annotations }}
  annotations:
    {{ toYaml .annotations }}
  {{- end }}
{{- end }}
{{- end }}
